### ISSUE TITLE
Add wood processing structures to cabin in the woods

### ISSUE THREAD

**Issue by mickvangelderen** [mickvangelderen/graveyard-keeper-issue-tracker#19]
https://steamcommunity.com/app/599140/discussions/0/1734336452558053581/

Not sure if this extremely necessary because some preparation to go on an excavation trip isn't bad. But at least [have the building construction costs be predictable](https://github.com/mickvangelderen/graveyard-keeper-issue-tracker/issues/18).

**Comment by Magichp** [comment]
You realize not everyone want that?

**Comment by mickvangelderen** [comment]
> You realize not everyone want that?

I do, that is why the description says "not sure".

Closing because the underlying issue is [https://github.com/mickvangelderen/graveyard-keeper-issue-tracker/issues/18](inconsistent building costs) which punishes planning instead of rewarding it. Setting up the excavation outpost would then continue to feel like an accomplishment.

**Comment by mickvangelderen** [comment]
@Magichp also, I do realize that because currently I'm the only one working on this issue tracker the issues might be opinionated. I try to cover things that I not fully support, assuming I acknowledge the existence of the problem, too to try and remain as unbiased as possible *and* include links to the original discussions I find.

**Comment by Magichp** [comment]
I just think it is VERY weird to start a a github issue tracker to help with bugs that imper gameplay, and add in the middle a request that is coming from a few people on a forum while completely ignoring all the pthers who disagree.

In the case that your issue tracker gets noticed or used by the devs, there is a high chance that they'll follow it blindly since it will already be coming from users. Except it is coming from a part of the users, effectively muting the others. You took a responsibility by opening this bug tracker, and which are displayed and which aren't are your first one to tackle. 

To put it simpy, this is a request, it has no place in an issue tracker.

**Comment by mickvangelderen** [comment]
You are right. I hope this issue tracker can grow and other people will chip in. The platform is better suited to keep track of issues than the steam discussions because of its labeling, closing and searching. The downside is only certain people will have or bother creating an account to chip in.

I closed this particular issue because I agreed with you.

**Comment by mickvangelderen** [comment]
I [added the *questionable* label](https://github.com/mickvangelderen/graveyard-keeper-issue-tracker/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Aquestionable+) to explicitly mark issues that need discussion. There were already more of them than I realize and I thank you @Magichp for making me realize this!

**Comment by mickvangelderen** [comment]
https://steamcommunity.com/app/599140/discussions/4/1734336452563675466/

**Comment by mickvangelderen** [comment]
https://steamcommunity.com/app/599140/discussions/4/1734336452572308145/

> Can you please enable the blueprint for the wedge crafting station for the campsite for the marble production, and can you also put a grind stone up there? Id prefer not ot have to make a dozen tools if possible :) Would also need a wood storage bin added as well.
